---
title: "listcolumn"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

set.seed(1)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## lists
```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```
 
```{r}
l = list(
  vec_numeric = 5:8,
  mat = matrix(1:8,2,4),
  vec_logical = c(TRUE, FALSE),
  summary = summary(rnorm(1000))
)

l
```
accessing list items

```{r}
l$vec_numeric

l[[3]]
```
## loops

write a 'for' loop

```{r}
list_norm = list(
  a = rnorm(20,5,4),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norm[[i]])
}

output[[1]]
output
```

## can we map 

```{r}
map(list_norm, mean_and_sd)
```

what about other functions
```{r}
map(list_norm, summary)
```
map variants


