---
title: "simulations"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

set.seed(1)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

```{r}
sim_mean_sd(n = 30)
```
how can we use this now 

write a for loop!
```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  output[[i]] = sim_mean_sd(n = 30)
}

bind_rows(output)
```

let's use list columns instead 

```{r}
sim_results_df =
  expand_grid(
  sample_size = 30,
  iteration = 1:100
) %>% 
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>% 
  unnest(estimate_df)
```

```{r}
sim_results_df %>% 
  ggplot(aes(x = mu_hat)) + geom_density()
```

## what abt changing sample size 

I need a input list with lots of sample sizes.

```{r}
sim_results_df =
  expand_grid(
  sample_size = c(30, 60, 120, 240),
  iteration = 1:100
) %>% 
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>% 
  unnest(estimate_df)
```

```{r}
sim_results_df %>% 
  mutate(
    sample_size = str_c("N =", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat, fill = sample_size)) +
  geom_violin()
```
```{r}
sim_results_df %>% 
  pivot_longer(
    mu_hat:sigma_hat,
    names_to = "parameter", 
    values_to = "estimate") %>% 
  group_by(parameter, sample_size) %>% 
  summarize(
    emp_mean = mean(estimate),
    emp_var = var(estimate)) 
```

## Let's see two inputs 
map2 function for 2 arguments, also can be used in map 
can only use .x and .y
cache = true don't run again when knitting
```{r, cache=TRUE}
sim_results_df =
  expand_grid(
  sample_size = c(30, 60, 120, 240),
  true_sigma = c(6,3),
  iteration = 1:100
) %>% 
  mutate(
    estimate_df = map2(.x = sample_size, .y = true_sigma, ~sim_mean_sd(n = .x, sigma = .y))
  ) %>% 
  unnest(estimate_df)
```

plot and see difference in sigma

```{r}
sim_results_df %>% 
  mutate(
    sample_size = str_c("N =", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat, fill = sample_size)) +
  geom_violin() +
  facet_grid( . ~ true_sigma)
```

