---
title: "writing funtions"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## z scores
 compute z score from a list of numbers 
```{r}
x_vec = rnorm(25, mean = 7, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)
```

```{r}
z_scores = function(x) {
  
  if(!is.numeric(x)) {
    stop("Z scores only work for numbers")
  }
  
  if(length(x) < 3) {
    stop("Z scores really work if you have three or more numbers")
  }
  z = (x - mean(x)) / sd(x)
  z
}
```

```{r}
z_scores(x = x_vec)

z_scores(x = 1:10)
```
## lets have multiple outputs 

lets have mean and standard deviation from the vector output 

```{r}
mean_and_sd = function(x) {
   
   if(!is.numeric(x)) {
    stop("Z scores only work for numbers")
  }
  
  if(length(x) < 3) {
    stop("Z scores really work if you have three or more numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}

mean_and_sd(x = x_vec)
mean_and_sd(x = 1:10)
```
lets start with some simulations 

```{r}
x_vec = rnorm(n = 25, mean = 7, sd = 4)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
tibble(
  mean = mean(x_vec),
  sd = sd(x_vec))
}
```

```{r}
sim_mean_sd(n= 5000, mu = 5, sigma = 7)
```
## fixing bad stuff

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

## write a function to get reviews 

```{r}
read_page_review = function(url) {
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```


use read review function to read from multiple pages

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_review(vec_urls[1]),
  read_page_review(vec_urls[2]),
  read_page_review(vec_urls[3]),
  read_page_review(vec_urls[4]),
  read_page_review(vec_urls[5])
)

dynamite_reviews
```

